package application;

/**
 * Creates the spaces on the board, which contain their number, and the value of
 * money a player may gain or lose when landing on that space.
 * 
 * @author Celia
 *
 */
public class Space {
	// The space number on the board: space zero is the starting space.
	private int spaceNum;

	// The value of money the player will gain or lose, randomly generated.
	private int spaceVal;

	/**
	 * Constructor.
	 * 
	 * @param num The index of the space in the spaceList.
	 */
	public Space(int num) {
		spaceNum = num;
		if (num == 0 || num == 47) {
			spaceVal = 0;
		} else {
			spaceVal = (int) ((102.0 * Math.random()) - 51.0);
		}
	}

	/**
	 * Gets the spaceNum generated by the constructor.
	 * 
	 * @see #constructor(int num)
	 * @return spaceNum The index of the space in spaceList.
	 */
	public int getSpaceNum() {
		return spaceNum;
	}

	/**
	 * Gets the spaceVal generated by the constructor.
	 * 
	 * @see #constructor(int num)
	 * @return spaceVal The money value the player may gain or lose when on the
	 *         space.
	 */
	public int getSpaceVal() {
		return spaceVal;
	}

	/**
	 * Sets the index of the space in spaceList.
	 * 
	 * @param spaceNum The intended index of the space.
	 */
	public void setSpaceNum(int spaceNum) {
		this.spaceNum = spaceNum;
	}

	/**
	 * Sets the amount of money a player may gain or lose on that space.
	 * 
	 * @param spaceVal The intended money value of the space.
	 */
	public void setSpaceVal(int spaceVal) {
		this.spaceVal = spaceVal;
	}

}
